# Generated by Django 3.0.6 on 2022-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinfo',
            name='idtag',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='meetinfo',
            name='topicno',
            field=models.IntegerField(default=1),
        ),
    ]
