# Generated by Django 3.0.6 on 2022-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_app', '0002_auto_20220405_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinfo',
            name='perma',
            field=models.IntegerField(default=1),
        ),
    ]
